---
name: "CI: Tests"

permissions: read-all

on:
  pull_request:

jobs:
  run-remote-image-docker-compose:
    strategy:
      matrix:
        module: ['default', 'external-network', 'cloudflare-tunnel']
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pull docker compose images
        run: docker compose pull

      - name: setup test environment
        run: .github/tests/setup/${{ matrix.module }}.sh

      - name: run tests
        run: .github/tests/${{ matrix.module }}.sh
