---
name: CI

permissions: read-all

on:
  pull_request:

jobs:
  docker-compose-lint:
    name: "Docker Compose self-lint"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: lint zammad docker compose file
        run: docker compose config

  super-linter:
    name: "Super Linter"
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint code base
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_YAML_PRETTIER: false

  tests:
    name: "Run tests with remote docker image"
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    strategy:
      matrix:
        module: ['default', 'add-external-network-to-nginx', 'add-cloudflare-tunnel']
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: pull docker compose images
        run: docker compose pull

      - name: set up test environment
        run: .github/tests/setup/${{ matrix.module }}.sh

      - name: run tests
        run: .github/tests/${{ matrix.module }}.sh
