name: ci

on:
  pull_request:

jobs:
  lint-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Bash scripts
        uses: docker://koalaman/shellcheck-alpine:v0.7.0
        with:
          args: .github/lint-scripts.sh

  install-docker-compose:
    name: install-docker-compose
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: lint-bash-scripts
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: get containers
        run: docker-compose pull
      - name: install
        run: docker-compose up -d
      - name: tests
        run: .github/tests.sh

